version: '3.3'

services:
  redis:
    # Adjust the build context to your needs targetting the created Dockerfile
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    # Run as privileged to allow the container to change the vm.overcommit_memory setting
    privileged: true
    volumes:
      - ./docker/data/redis:/data
  web:
    image: jlucasamorim/prodsistem-staging:latest
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    links:
      - redis