version: '3.3'

services:
  redis:
    image: redis:alpine
    container_name: prodcontrol-staging-redis
    restart: always
    ports:
      - "6379:6379"
    privileged: true
    volumes:
      - ./docker/data/redis-staging:/data
    networks:
      - prodcontrol-staging-network
    # Only start if REDIS_HOST is not set or is 'redis'
    profiles:
      - local-redis
  web:
    image: jlucasamorim/prodsistem-staging:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_REGION: us-east-2
      NODE_ENV: production
      PORT: 8080
    links:
      - redis
    # Network configuration
    networks:
      - prodcontrol-staging-network

networks:
  prodcontrol-staging-network:
    driver: bridge 