version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: prodcontrol-master
      POSTGRES_USER: prodcontrol-master
      POSTGRES_DB: prodcontrol-master
  web:
    image: jlucasamorim/prodsistem-preview:latest
    ports:
      - "3000:3000"
    networks:
      - webnet
    restart: always
    environment:
      DB_USER: prodcontrol-master
      DB_PASSWORD: prodcontrol-master
      DB_HOST: db
      DB_PORT: 5432
      DB: prodcontrol-master
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS:
      NODE_ENV: production
    links:
      - db
      - redis
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    links:
      - web:web
networks:
  webnet:
