version: '3.3'

services:
  redis:
    # Adjust the build context to your needs targetting the created Dockerfile
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    # Run as privileged to allow the container to change the vm.overcommit_memory setting
    privileged: true
    volumes:
      - ./docker/data/redis:/data
  web:
    image: jlucasamorim/prodsistem-prod:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_REGION: us-east-2
      NODE_ENV: production
      PORT: 8080
    links:
      - redis