version: '3.3'

services:
  redis:
    image: redis:6.2-alpine
  web:
    image: jlucasamorim/prodsistem-prod:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_USER:
      REDIS_DB: 0
      NODE_ENV: production
      PORT: 8080
    links:
      - redis